export const salesRules = {
  maxResponseLines: 5,
  maxEmojisPerMessage: 1,
  preferNoEmoji: true,
  delayMinSeconds: 8,
  delayMaxSeconds: 25,
  positiveConfirmationKeywords: [
    "sim",
    "claro",
    "pode",
    "manda",
    "quero ver",
    "pode mandar",
    "manda ai",
    "manda aí",
    "sim pode",
    "lógico",
    "com certeza",
    "bora",
    "vamos",
    "ok",
    "okay",
    "pode ser",
  ],
  humanNeededKeywords: [
    "reembolso",
    "cancelar",
    "problema com pagamento",
    "não recebi",
    "nao recebi",
    "reclamação",
    "suporte",
    "atendente",
    "falar com humano",
    "quero falar com alguém",
    "problema no pagamento",
    "problema com pagamento",
    "pagamento não foi",
    "pagamento nao foi",
    "paguei e não recebi",
    "paguei e nao recebi",
    "golpe",
    "é confiável",
    "e confiavel",
    "é seguro",
    "e seguro",
    "confiança",
    "confianca",
  ],
  stopContactKeywords: [
    "não quero",
    "nao quero",
    "pare",
    "parar",
    "sair",
    "remover",
    "não me chama",
    "nao me chama",
    "não tenho interesse",
    "nao tenho interesse",
  ],
  buyIntentKeywords: [
    "quero comprar",
    "comprar",
    "quero adquirir",
    "quero o pacote",
    "quero pagar",
    "como compra",
    "como faço para comprar",
    "quero um",
    "manda o link",
    "me manda o link",
    "envia o link",
    "quero o link",
    "link de pagamento",
  ],
  objectionExpensiveKeywords: [
    "caro",
    "muito caro",
    "não tenho dinheiro",
    "sem condições",
    "muito dinheiro",
    "preço alto",
    "não vale",
    "caríssimo",
  ],
  objectionThinkKeywords: [
    "vou pensar",
    "vou ver",
    "depois eu vejo",
    "mais tarde",
    "vou analisar",
    "preciso pensar",
    "vou considerar",
    "talvez",
    "não sei",
  ],
};
